services:
  traefik:
    image: traefik:v3.7
    container_name: "traefik"
    command:
      - "--api.insecure=true" # Not securing Traefik dashboard since logs will be genreated separately, default unsecure dashboard will work fine as it may never be accessed.
      - "--providers.docker=true"
      - "--providers.docker.network=traefik-net"
      - "--entrypoints.web.address=:80" # Entrypoint
      - "--providers.docker.exposedbydefault=false" # Disable any container to get exposed to traefik and later explicitly enable specific container like Frontend and Backend.
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080" # For traefik dashboard
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker sock binding (Not secure but require for service discovery). That's why exposedbydefault=false
    
  backend:
    # build:              # If running locally
    #   context: .
    #   dockerfile: docker/Dockerfile.backend
    # image: backend-image:latest         # Pull from DockerHub
    image: harshitrajsinha/spotify-backend:90332252c774ed2aebf15bb5945b1496d6b13e9f
    # Not to specify container_name and ports as they will create conflicts during scale up.
    expose:
      - "8000"
    env_file:
      - backend/.env
    restart: unless-stopped
    volumes:
      - /opt/certs/global-bundle.pem:/app/certs/global-bundle.pem:ro
    ############################   CPU and memory limit required
    deploy:
      replicas: 1 # Pre-allocate replicas based on capability of t3a.medium because auto-scaling is not possible in docker
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true" # Enabling will allow exposing "this" container to traefik
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.priority=10"
  
  frontend:
    # build:              # If running locally
    #   context: .
    #   dockerfile: docker/Dockerfile.frontend
    #   secrets:
    #     - spotify-frontend-env
    # image: frontend-image:latest
    image: harshitrajsinha/spotify-frontend:79f1cb8be42e972f8ace60d59f86e650e70bdff2
    expose:
      - "80"
    networks:
      - traefik-net
    restart: unless-stopped
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true" # Enabling will allow exposing "this" container to traefik
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.priority=1"
    depends_on:
      - backend

networks:
  traefik-net:
    name: traefik-net
secrets:
  spotify-frontend-env:
    file: frontend/.env
