services:
  traefik:
    image: traefik:v3.7.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      # - "8000:8000"
      - "8080:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: backend-image:latest
    expose:
      - "8000"
    # ports:
    #   - "8000" # Internal-only port to avoid "port already allocated" issue
    env_file:
      - backend/.env
    deploy:
      replicas: 1
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      secrets:
        - spotify-frontend-env
    image: frontend-image:latest
    # ports:
    #   - "80" # Internal-only port to avoid "port already allocated" issue
    expose:
      - "80"
    deploy:
      replicas: 1
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.backend.priority=10"
    restart: unless-stopped


networks:
  app-network:
    driver: bridge
secrets:
  spotify-frontend-env:
    file: frontend/.env
