FROM node:24.16.0-alpine3.23

WORKDIR /app

RUN apk add --no-cache curl

COPY backend/package.json backend/package-lock.json ./

RUN npm ci

COPY ./backend/ .

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl -f http://localhost:8000/api/health ||  exit 1

USER node

CMD ["node", "src/index.js"]